blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path(
        route='about-me',
        view=TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
    path('', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='blog'
    ),
    path(
        route='posts/<slug:url>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/save_comment',
        view=views.save_comment,
        name='save_comment'
    ),
]

posts/models.py
"""Posts models."""

# Django
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from categories.models import Category


class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    profile = models.ForeignKey('users.Profile', on_delete=models.PROTECT)

    title = models.CharField(max_length=255)
    image_header = models.ImageField(upload_to='posts/photos')
    post = RichTextField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    is_draft = models.BooleanField(default=True)
    url = models.SlugField(max_length=255, unique=True)
    views = models.PositiveIntegerField(default=0)
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ('title',)
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

    def save(self, *args, **kwargs):
        self.url = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

# Models
from posts.models import Post
from categories.models import Category
from comments.models import Comment

# Forms
from comments.forms import CreateCommentForm


class PostsFeedView(ListView):
    """Index."""
    template_name = 'posts/index.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 10
    context_object_name = 'posts'
    queryset = Post.objects.filter(is_draft=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class PostDetailView(DetailView):
    """Detail post."""
    template_name = 'posts/detail.html'
    model = Post
    context_object_name = 'post'
    slug_field = 'url'
    slug_url_kwarg = 'url'

    def get_queryset(self):
        return Post.objects.filter(is_draft=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['comments'] = Comment.objects.filter(post=self.get_object()).all()
        context['form_comments'] = CreateCommentForm()
        return context


@login_required
def save_comment(request):
    if request.method == 'POST':
        url = request.POST['url']
        post = {
            'user': request.user.id,
            'profile': request.user.id,
            'comment': request.POST['comment'],
            'post': request.POST['post']
        }
        form = CreateCommentForm(post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', url=url)
    else:
        return HttpResponse(status=405)
    return HttpResponse(status=500)

templates/posts/detail.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4">{{post.title}}</h1>
        <p class="lead">
          por
          <a href="#">{{post.user.username}}</a>
        </p>
        <hr>
        <p>Создан {{post.created}}</p>
        <hr>
        <img class="img-fluid rounded" src="{{ post.image_header.url }}" alt="">
        <hr>
        <p class="lead">{{post.post|safe}}</p>
        <hr>
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Оставить комментарий:</h5>
          <div class="card-body">
            <form method="POST" action="{% url "posts:save_comment" %}">
              {% csrf_token %}
              <input type="hidden" name="url" value="{{post.url}}" />
              <input type="hidden" name="post" value="{{post.id}}" />
              <div class="form-group">
                <textarea class="form-control" name="comment" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
        {% endif %}
        {% for comment in comments %}
        <div class="media mb-4">
          {% if comment.user.profile.photo %}
          <img class="d-flex mr-3 rounded-circle" width="50px" height="50px" src="/media/{{ comment.user.profile.photo }}" alt="">
          {% else %}
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          {% endif %}
          <div class="media-body">
            <h5 class="mt-0">{{comment.user.username}}</h5>
            {{comment.comment}}
          </div>
        </div>
        {% endfor %}
      </div>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-8">

        <h1 class="my-4">Simple Blog
        </h1>
        {% for post in posts %}
        <div class="card mb-4">
          <img class="card-img-top" src="{{ post.image_header.url }}" alt="Card image cap">
          <div class="card-body">
            <h2 class="card-title">{{post.title}}</h2>
            <p class="card-text">{{post.post|safe|truncatechars:300}}</p>
            <a href="{% url 'posts:detail' post.url%}" class="btn btn-primary">Leer más &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Escrito el {{post.created}}
            <a href="#">{{post.user.username}}</a>
          </div>
        </div>
        {% endfor %}
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
          </li>
        </ul>

      </div>
{% endblock %}