blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path(
        route='about-me',
        view=TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
    path('', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

urlpatterns = [
    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='register',
        view=views.SignupView.as_view(),
        name='register'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='register_completed/',
        view=TemplateView.as_view(template_name='users/registerok.html'),
        name='registerok'
    ),
]

users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    website = models.URLField(max_length=200, blank=True)

    photo = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        """Return username."""
        return self.user.username

users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )
    username = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.TextInput()
    )
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Пароли не совпадают.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
from django.shortcuts import render

from django.views.generic import FormView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views

# Forms
from users.forms import SignupForm


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/register.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:registerok')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = '/'

templates/users/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Simple blog - Login{% endblock %}</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
</head>
<body class="text-center">
    {% block content %}{% endblock %}
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}
{% block content %}
<form method="POST" action="{% url "users:login" %}" class="form-signin">
    {% csrf_token %}
    <h1><a href="#" class="title-link">Simple Blog</a></h1>
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    <label for="id_username" class="sr-only">Пользователь</label>
    <input type="text" id="id_username" class="form-control" placeholder="Пользователь" name="username" required autofocus>
    <label for="id_password" class="sr-only">Пароль</label>
    <input type="password" id="id_password" class="form-control" placeholder="Пароль" name="password" required>
    <div class="checkbox mb-3"></div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <p class="mt-5 mb-3 text-muted">&copy; Simple Blog {% now "Y" %}</p>
    </form>
{% endblock %}

templates/users/register.html
{% extends "users/base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<form class="form-signin" method="POST">
    {% csrf_token %}
    <h1><a href="#" class="title-link">Простой блог</a></h1>
    <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
    <label for="id_email" class="sr-only">Email</label>
    <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" required autofocus>
    <label for="id_username" class="sr-only">Имя пользователя</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="Имя пользователя" required>
    <label for="inputPassword" class="sr-only">Пароль</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Пароль" required>
    <label for="inputPassword" class="sr-only">Повторите пароль</label>
    <input type="password" name="password_confirmation" id="id_password_confirmation" class="form-control" placeholder="Повторите пароль" required>
    <div class="checkbox mb-3"></div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <p class="mt-5 mb-3 text-muted">&copy; Simple Blog {% now "Y" %}</p>
    </form>
{% endblock %}

templates/users/registerok.html
{% extends "users/base.html" %}
{% block title %}Регистрация завершена{% endblock %}
{% block content %}
<main role="main" class="container">
   <div class="starter-template">
      <h1>Пользователь успешно создан</h1>
      <p class="lead">Если страница не будет перенаправлена в течение 5 секунд, нажмите ссылку<a href="{% url 'users:login' %}">здесь</a></p>
   </div>
</main>
<script>
   setTimeout(function(){ 
       window.location.replace("{% url 'users:login' %}");
   }, 5000);
</script>
{% endblock %}